// Command unicodegen generates committed Unicode tables and conformance fixtures
package main

import (
	"bufio"
	"bytes"
	"errors"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"slices"
	"sort"
	"strconv"
	"strings"
	"unicode/utf8"
)

const unicodeVersion = "17.0.0"

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "unicodegen:", err)
		os.Exit(1)
	}
}

func run() error {
	var dataDirectory string
	var output string
	var fixtureOutput string
	flag.StringVar(&dataDirectory, "data-dir", "", "directory containing Unicode source data")
	flag.StringVar(&output, "out", "", "generated Go output path")
	flag.StringVar(&fixtureOutput, "fixture-out", "", "optional generated grapheme fixture path")
	flag.Parse()
	if dataDirectory == "" || output == "" {
		return errors.New("-data-dir and -out are required")
	}

	data, err := loadUnicodeData(dataDirectory)
	if err != nil {
		return err
	}
	source, err := data.goSource()
	if err != nil {
		return err
	}
	if err := writeIfChanged(output, source); err != nil {
		return err
	}
	if fixtureOutput != "" {
		fixture, err := graphemeFixture(filepath.Join(dataDirectory, "GraphemeBreakTest.txt"))
		if err != nil {
			return err
		}
		if err := writeIfChanged(fixtureOutput, fixture); err != nil {
			return err
		}
	}
	return nil
}

type codePointRange struct {
	start rune
	end   rune
}

type valueRange struct {
	start rune
	end   rune
	value uint8
}

type unicodeData struct {
	graphemeBreak        []valueRange
	indicConjunctBreak   []valueRange
	eastAsianWidth       []valueRange
	extendedPictographic []codePointRange
	emojiPresentation    []codePointRange
	variationBases       []rune
	rgiEmojiSequences    [][]rune
}

func loadUnicodeData(root string) (unicodeData, error) {
	grapheme, err := source(root, "GraphemeBreakProperty.txt", "17.0.0")
	if err != nil {
		return unicodeData{}, err
	}
	derived, err := source(root, "DerivedCoreProperties.txt", "17.0.0")
	if err != nil {
		return unicodeData{}, err
	}
	eastAsian, err := source(root, "EastAsianWidth.txt", "17.0.0")
	if err != nil {
		return unicodeData{}, err
	}
	emojiData, err := source(root, "emoji-data.txt", "17.0")
	if err != nil {
		return unicodeData{}, err
	}
	emojiSequences, err := source(root, "emoji-sequences.txt", "17.0")
	if err != nil {
		return unicodeData{}, err
	}
	emojiZWJ, err := source(root, "emoji-zwj-sequences.txt", "17.0")
	if err != nil {
		return unicodeData{}, err
	}
	emojiVariation, err := source(root, "emoji-variation-sequences.txt", "17.0")
	if err != nil {
		return unicodeData{}, err
	}

	graphemeBreak, err := parseTwoFieldProperties(grapheme, func(property string) (uint8, bool) {
		values := map[string]uint8{
			"CR": 1, "LF": 2, "Control": 3, "Extend": 4, "ZWJ": 5,
			"Regional_Indicator": 6, "Prepend": 7, "SpacingMark": 8,
			"L": 9, "V": 10, "T": 11, "LV": 12, "LVT": 13,
		}
		value, ok := values[property]
		return value, ok
	})
	if err != nil {
		return unicodeData{}, err
	}
	indicConjunctBreak, err := parseIndicConjunctBreak(derived)
	if err != nil {
		return unicodeData{}, err
	}
	eastAsianWidth, err := parseTwoFieldProperties(eastAsian, func(property string) (uint8, bool) {
		switch property {
		case "A":
			return 1, true
		case "W", "F":
			return 2, true
		default:
			return 0, false
		}
	})
	if err != nil {
		return unicodeData{}, err
	}
	extendedPictographic, err := parseBinaryProperty(emojiData, "Extended_Pictographic")
	if err != nil {
		return unicodeData{}, err
	}
	emojiPresentation, err := parseBinaryProperty(emojiData, "Emoji_Presentation")
	if err != nil {
		return unicodeData{}, err
	}
	variationBases, err := parseVariationBases(emojiVariation)
	if err != nil {
		return unicodeData{}, err
	}
	sequences, err := parseEmojiSequences(emojiSequences)
	if err != nil {
		return unicodeData{}, err
	}
	zwjSequences, err := parseEmojiSequences(emojiZWJ)
	if err != nil {
		return unicodeData{}, err
	}
	sequences = append(sequences, zwjSequences...)
	slices.SortFunc(sequences, slices.Compare)
	sequences = slices.CompactFunc(sequences, slices.Equal)

	return unicodeData{
		graphemeBreak:        graphemeBreak,
		indicConjunctBreak:   indicConjunctBreak,
		eastAsianWidth:       eastAsianWidth,
		extendedPictographic: extendedPictographic,
		emojiPresentation:    emojiPresentation,
		variationBases:       variationBases,
		rgiEmojiSequences:    sequences,
	}, nil
}

func (data unicodeData) goSource() ([]byte, error) {
	var output bytes.Buffer
	output.WriteString("// Code generated by unicodegen from Unicode 17.0.0 data; DO NOT EDIT.\n\n")
	output.WriteString("// Unicode data is distributed under Unicode License v3; see UNICODE-LICENSE.\n\n")
	output.WriteString("package text\n\n")
	output.WriteString("const unicodeVersion = \"17.0.0\"\n\n")
	writeValueRanges(&output, "graphemeBreakRanges", data.graphemeBreak)
	writeValueRanges(&output, "indicConjunctBreakRanges", data.indicConjunctBreak)
	writeValueRanges(&output, "eastAsianWidthRanges", data.eastAsianWidth)
	writeRanges(&output, "extendedPictographicRanges", data.extendedPictographic)
	writeRanges(&output, "emojiPresentationRanges", data.emojiPresentation)
	output.WriteString("var emojiVariationBases = [...]rune{\n")
	for _, codePoint := range data.variationBases {
		fmt.Fprintf(&output, "0x%X,\n", codePoint)
	}
	output.WriteString("}\n\n")
	output.WriteString("var rgiEmojiSequences = [...][]rune{\n")
	for _, sequence := range data.rgiEmojiSequences {
		output.WriteByte('{')
		for index, codePoint := range sequence {
			if index != 0 {
				output.WriteString(", ")
			}
			fmt.Fprintf(&output, "0x%X", codePoint)
		}
		output.WriteString("},\n")
	}
	output.WriteString("}\n")
	formatted, err := format.Source(output.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated Go source: %w", err)
	}
	return formatted, nil
}

func source(root, name, marker string) (string, error) {
	path := filepath.Join(root, name)
	input, err := os.ReadFile(path)
	if err != nil {
		return "", fmt.Errorf("read %s: %w", path, err)
	}
	lines := strings.Split(string(input), "\n")
	found := false
	for _, line := range lines[:min(len(lines), 30)] {
		if strings.Contains(line, marker) {
			found = true
			break
		}
	}
	if !found {
		return "", fmt.Errorf("%s is not Unicode %s data", path, marker)
	}
	return string(input), nil
}

func scanData(input string, visit func(int, []string) error) error {
	scanner := bufio.NewScanner(strings.NewReader(input))
	for lineNumber := 1; scanner.Scan(); lineNumber++ {
		data, _, _ := strings.Cut(scanner.Text(), "#")
		data = strings.TrimSpace(data)
		if data == "" {
			continue
		}
		fields := strings.Split(data, ";")
		for index := range fields {
			fields[index] = strings.TrimSpace(fields[index])
		}
		if err := visit(lineNumber, fields); err != nil {
			return err
		}
	}
	return scanner.Err()
}

func parseTwoFieldProperties(input string, propertyValue func(string) (uint8, bool)) ([]valueRange, error) {
	var ranges []valueRange
	err := scanData(input, func(line int, fields []string) error {
		if len(fields) != 2 {
			return fmt.Errorf("line %d: expected two fields", line)
		}
		value, wanted := propertyValue(fields[1])
		if !wanted {
			return nil
		}
		rangeValue, err := parseRange(fields[0], line)
		if err != nil {
			return err
		}
		ranges = append(ranges, valueRange{start: rangeValue.start, end: rangeValue.end, value: value})
		return nil
	})
	return mergeValueRanges(ranges), err
}

func parseIndicConjunctBreak(input string) ([]valueRange, error) {
	var ranges []valueRange
	err := scanData(input, func(line int, fields []string) error {
		if len(fields) != 3 || fields[1] != "InCB" {
			return nil
		}
		values := map[string]uint8{"Consonant": 1, "Extend": 2, "Linker": 3}
		value, wanted := values[fields[2]]
		if !wanted {
			return nil
		}
		rangeValue, err := parseRange(fields[0], line)
		if err != nil {
			return err
		}
		ranges = append(ranges, valueRange{start: rangeValue.start, end: rangeValue.end, value: value})
		return nil
	})
	return mergeValueRanges(ranges), err
}

func parseBinaryProperty(input, wanted string) ([]codePointRange, error) {
	var ranges []codePointRange
	err := scanData(input, func(line int, fields []string) error {
		if len(fields) != 2 {
			return fmt.Errorf("line %d: expected two fields", line)
		}
		if fields[1] != wanted {
			return nil
		}
		rangeValue, err := parseRange(fields[0], line)
		if err != nil {
			return err
		}
		ranges = append(ranges, rangeValue)
		return nil
	})
	return mergeRanges(ranges), err
}

func parseVariationBases(input string) ([]rune, error) {
	bases := make(map[rune]struct{})
	err := scanData(input, func(line int, fields []string) error {
		if len(fields) < 2 {
			return fmt.Errorf("line %d: expected variation fields", line)
		}
		codePoints, err := parseCodePoints(fields[0], line)
		if err != nil {
			return err
		}
		if len(codePoints) != 2 || (codePoints[1] != 0xFE0E && codePoints[1] != 0xFE0F) {
			return fmt.Errorf("line %d: unsupported variation sequence", line)
		}
		bases[codePoints[0]] = struct{}{}
		return nil
	})
	result := make([]rune, 0, len(bases))
	for base := range bases {
		result = append(result, base)
	}
	slices.Sort(result)
	return result, err
}

func parseEmojiSequences(input string) ([][]rune, error) {
	var sequences [][]rune
	err := scanData(input, func(line int, fields []string) error {
		if len(fields) < 2 {
			return fmt.Errorf("line %d: expected emoji sequence fields", line)
		}
		if start, end, ranged := strings.Cut(fields[0], ".."); ranged {
			first, err := parseScalar(start, line)
			if err != nil {
				return err
			}
			last, err := parseScalar(end, line)
			if err != nil {
				return err
			}
			if first > last {
				return fmt.Errorf("line %d: descending sequence range", line)
			}
			for codePoint := first; codePoint <= last; codePoint++ {
				sequences = append(sequences, []rune{codePoint})
			}
			return nil
		}
		codePoints, err := parseCodePoints(fields[0], line)
		if err != nil {
			return err
		}
		sequences = append(sequences, codePoints)
		return nil
	})
	return sequences, err
}

func parseCodePoints(value string, line int) ([]rune, error) {
	fields := strings.Fields(value)
	codePoints := make([]rune, len(fields))
	for index, field := range fields {
		codePoint, err := parseScalar(field, line)
		if err != nil {
			return nil, err
		}
		codePoints[index] = codePoint
	}
	return codePoints, nil
}

func parseRange(value string, line int) (codePointRange, error) {
	start, end, ranged := strings.Cut(value, "..")
	if !ranged {
		end = start
	}
	first, err := parseScalar(start, line)
	if err != nil {
		return codePointRange{}, err
	}
	last, err := parseScalar(end, line)
	if err != nil {
		return codePointRange{}, err
	}
	if first > last {
		return codePointRange{}, fmt.Errorf("line %d: descending code point range", line)
	}
	return codePointRange{start: first, end: last}, nil
}

func parseScalar(value string, line int) (rune, error) {
	parsed, err := strconv.ParseUint(strings.TrimSpace(value), 16, 32)
	if err != nil {
		return 0, fmt.Errorf("line %d: invalid code point %s: %w", line, value, err)
	}
	codePoint := rune(parsed)
	if !utf8.ValidRune(codePoint) {
		return 0, fmt.Errorf("line %d: invalid Unicode scalar U+%X", line, parsed)
	}
	return codePoint, nil
}

func mergeRanges(ranges []codePointRange) []codePointRange {
	sort.Slice(ranges, func(i, j int) bool { return ranges[i].start < ranges[j].start })
	merged := make([]codePointRange, 0, len(ranges))
	for _, current := range ranges {
		if len(merged) != 0 && current.start <= merged[len(merged)-1].end+1 {
			merged[len(merged)-1].end = max(merged[len(merged)-1].end, current.end)
			continue
		}
		merged = append(merged, current)
	}
	return merged
}

func mergeValueRanges(ranges []valueRange) []valueRange {
	sort.Slice(ranges, func(i, j int) bool { return ranges[i].start < ranges[j].start })
	merged := make([]valueRange, 0, len(ranges))
	for _, current := range ranges {
		if len(merged) != 0 && current.value == merged[len(merged)-1].value && current.start == merged[len(merged)-1].end+1 {
			merged[len(merged)-1].end = current.end
			continue
		}
		merged = append(merged, current)
	}
	return merged
}

func writeValueRanges(output *bytes.Buffer, name string, ranges []valueRange) {
	fmt.Fprintf(output, "var %s = [...]valueRange{\n", name)
	for _, rangeValue := range ranges {
		fmt.Fprintf(output, "{start: 0x%X, end: 0x%X, value: %d},\n", rangeValue.start, rangeValue.end, rangeValue.value)
	}
	output.WriteString("}\n\n")
}

func writeRanges(output *bytes.Buffer, name string, ranges []codePointRange) {
	fmt.Fprintf(output, "var %s = [...]codePointRange{\n", name)
	for _, rangeValue := range ranges {
		fmt.Fprintf(output, "{start: 0x%X, end: 0x%X},\n", rangeValue.start, rangeValue.end)
	}
	output.WriteString("}\n\n")
}

func graphemeFixture(path string) ([]byte, error) {
	input, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", path, err)
	}
	if !strings.Contains(string(input[:min(len(input), 4096)]), unicodeVersion) {
		return nil, fmt.Errorf("%s is not Unicode %s data", path, unicodeVersion)
	}

	var output bytes.Buffer
	output.WriteString("# Generated from Unicode 17.0.0 GraphemeBreakTest.txt\n")
	output.WriteString("# Distributed under the Unicode License v3; see UNICODE-LICENSE\n")
	output.WriteString("nagi-fixture-v1\ttext-grapheme-break\n")
	scanner := bufio.NewScanner(bytes.NewReader(input))
	caseNumber := 0
	for lineNumber := 1; scanner.Scan(); lineNumber++ {
		data, _, _ := strings.Cut(scanner.Text(), "#")
		data = strings.TrimSpace(data)
		if data == "" {
			continue
		}
		caseNumber++
		var fixtureText strings.Builder
		var boundaries []int
		byteOffset := 0
		for _, token := range strings.Fields(data) {
			switch token {
			case "÷":
				if len(boundaries) == 0 || boundaries[len(boundaries)-1] != byteOffset {
					boundaries = append(boundaries, byteOffset)
				}
			case "×":
			default:
				codePoint, err := parseScalar(token, lineNumber)
				if err != nil {
					return nil, err
				}
				byteOffset += utf8.RuneLen(codePoint)
				fmt.Fprintf(&fixtureText, "\\u{%X}", codePoint)
			}
		}
		boundaryFields := make([]string, len(boundaries))
		for index, boundary := range boundaries {
			boundaryFields[index] = strconv.Itoa(boundary)
		}
		fmt.Fprintf(&output, "unicode-%04d\ttext=%s\tboundaries=%s\n", caseNumber, fixtureText.String(), strings.Join(boundaryFields, ","))
	}
	if err := scanner.Err(); err != nil {
		return nil, fmt.Errorf("scan %s: %w", path, err)
	}
	return output.Bytes(), nil
}

func writeIfChanged(path string, contents []byte) error {
	existing, err := os.ReadFile(path)
	if err == nil && bytes.Equal(existing, contents) {
		return nil
	}
	if err := os.WriteFile(path, contents, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}
